export enum MessageType {
  SET_SESSION = 'SET_SESSION',
  REMOVE_SESSION = 'REMOVE_SESSION',

  GENERATE_REQUEST = 'GENERATE_REQUEST',
  GENERATE_RESPONSE = 'GENERATE_RESPONSE',
  GENERATE_ERROR = 'GENERATE_ERROR'
}