const LINKEDIN_JOB_DESCRIPTION = `div.jobs-description`;
const LINKEDIN_JOB_DESCRIPTION_CONTENT = `div.jobs-description-content__text`;

const SPOT_BOX_ROOT_CLASSNAME = `spot-box-root`;
const SPOT_BOX_ROOT = `div.${SPOT_BOX_ROOT_CLASSNAME}`;

export {
  LINKEDIN_JOB_DESCRIPTION,
  LINKEDIN_JOB_DESCRIPTION_CONTENT,
  SPOT_BOX_ROOT_CLASSNAME,
  SPOT_BOX_ROOT
};