const LINKEDIN_JOB_DESCRIPTION = `div.jobs-description`;
const LINKEDIN_JOB_DESCRIPTION_CONTAINER = `${LINKEDIN_JOB_DESCRIPTION} > article.jobs-description__container`;
const LINKEDIN_JOB_DESCRIPTION_CONTENT = `div.jobs-description-content__text`;
const LINKEDIN_JOB_DESCRIPTION_FOOTER = `${LINKEDIN_JOB_DESCRIPTION} > footer`;

const SPOT_BOX_WRAPPER = `div.spot-box-wrapper`;

export {
  LINKEDIN_JOB_DESCRIPTION_CONTAINER,
  LINKEDIN_JOB_DESCRIPTION_CONTENT,
  LINKEDIN_JOB_DESCRIPTION_FOOTER,
  SPOT_BOX_WRAPPER
};